sources:
  - name: dev_layer
    schema: dev_layer
    description: Raw data loaded from the csv containing order data - fact table
            
    tables:
      - name: dim_customer
        columns:
          - name: index
            data_type: int
          - name: customer_id
            data_type: varchar
          - name: first_name
            data_type: varchar
          - name: last_name
            data_type: varchar
          - name: company
            data_type: varchar
          - name: city
            data_type: varchar
          - name: country
            data_type: varchar
          - name: phone_1
            data_type: varchar
          - name: phone_2
            data_type: varchar
          - name: email
            data_type: varchar
          - name: subscription_date
            data_type: date
          - name: web_site
            data_type: varchar
          - name: last_updated_at
            data_type: timestamp_NTZ